config/routes.rb
Rails.application.routes.draw do

  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :charges, only: [:new, :create]
  # devise_for :users
  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :line_items, only: [:create, :update, :destroy]
  root to: 'products#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for line_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency line_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: line_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", line_item, { data: { confirm: "Are you sure you wish to delete the product '#{line_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency line_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@line_item.nil? && @line_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @line_items.size == 0 %>
  <p class="text-center">
    There are no items in your cart! Head over to <%= link_to "the main page", root_path %> to add some.
  </p>
<% else %>
  <% @line_items.each do |line_item| %>
    <%= render 'carts/cart_row', product: line_item.product, line_item: line_item, show_total: true %>
  <% end %>
  <div class="col-xs-8 text-right">
    <div class="btn-group">
      <%= link_to "Checkout", new_charge_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>